# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticazione', '0002_auto_20160117_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utenza',
            name='ultimo_accesso',
        ),
    ]
